using NUnit.Framework;
using UnityEngine;
using Cog;

namespace Cog.Tests
{
    public class CogNPCTests
    {
        // These tests need a GameObject in the scene to work.
        // They test the component's configuration, not runtime behavior.

        [Test]
        public void AutoGeneratedNpcId_IsNotEmpty()
        {
            var go = new GameObject("TestNPC");
            var npc = go.AddComponent<CogNPC>();
            // npcId auto-generates in Start(), but before Start it's empty or set
            // If empty, Start() would generate one
            if (string.IsNullOrEmpty(npc.npcId))
            {
                npc.npcId = System.Guid.NewGuid().ToString("N")[..8];
            }
            Assert.IsNotEmpty(npc.npcId);
            Object.DestroyImmediate(go);
        }

        [Test]
        public void ThinkCooldown_DefaultValue()
        {
            var go = new GameObject("TestNPC");
            var npc = go.AddComponent<CogNPC>();
            Assert.AreEqual(5f, npc.thinkCooldown);
            Object.DestroyImmediate(go);
        }

        [Test]
        public void ObservationRadius_DefaultValue()
        {
            var go = new GameObject("TestNPC");
            var npc = go.AddComponent<CogNPC>();
            Assert.AreEqual(5f, npc.observationRadius);
            Object.DestroyImmediate(go);
        }

        [Test]
        public void AutoObserve_DefaultTrue()
        {
            var go = new GameObject("TestNPC");
            var npc = go.AddComponent<CogNPC>();
            Assert.IsTrue(npc.autoObserve);
            Object.DestroyImmediate(go);
        }

        [Test]
        public void Profile_CanBeAssigned()
        {
            var go = new GameObject("TestNPC");
            var npc = go.AddComponent<CogNPC>();
            npc.profile = CogPersonalityProfile.CreateArchivist();
            Assert.IsNotNull(npc.profile);
            Assert.AreEqual("Archibald", npc.profile.npcName);
            Object.DestroyImmediate(go);
        }
    }
}
